# Site settings
title: Yves Chiong
email: yveschiongdev@gmail.com
url: https://yveschiong.github.io
description: "Portfolio website for Yves Chiong"
keywords: "android, designer, developer"
skills: "Android Developer - UI/UX Designer - Gaming Enthusiast"
meta_author: Chiong Yves

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6C648B
  primary-rgb: "108,100,139"
  secondary: 233237
  secondary-dark: 18121E

# Footer settings
footer:
  copyright: Yves Chiong
  social: Find me elsewhere

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/yves.chiong
  - title: bitbucket
    url: http://bitbucket.org/yveschiong
  - title: github
    url: http://github.com/yveschiong

# Build settings
markdown: kramdown
permalink: pretty
